@OsuApi_HostAddress = http://localhost:23316

POST {{OsuApi_HostAddress}}/calculate
Content-Type: application/json

{
  "file": "/home/spring/Documents/Fujikawa Chiai - 1000-nen Ai (Cibed) [Believe].osu",
  "mode": "osu",
  "score": {
    "accuracy": 0.9985,
    "legacy_total_score": 74063430,
    "max_combo": 1794,
    "statistics": {
      "great": 1344,
      "ok": 3,
      "meh": 0,
      "miss": 0
    },
    "mods": [{"acronym": "CL"}]
  }
}

###

POST {{OsuApi_HostAddress}}/calculate
Content-Type: application/json

{
  "file": "/home/spring/Documents/Fujikawa Chiai - 1000-nen Ai (Cibed) [Believe].osu",
  "mode": "osu",
  "score": {
    "mods": [{"acronym": "DT"}]
  }
}

###

POST {{OsuApi_HostAddress}}/calculate
Content-Type: application/json

{
  "file": "/home/spring/Documents/Fujikawa Chiai - 1000-nen Ai (Cibed) [Believe].osu",
  "mode": "osu",
  "score": {
    "mods": [
      {
        "acronym": "DT",
        "settings": {
          "speed_change": 1.1
        }
      }
    ]
  }
}

###
